[project]
name = "instruct-glm-llama-3-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black[jupyter]>=24.10.0",
    "ogb>=1.3.6",
    "rich>=13.9.4",
]
